version: '3.7'

services:
  database:
    container_name: messenger-notification-db
    image: postgres:alpine
    ports:
      - '5403:5432'
    environment:
      - POSTGRES_DB=messenger-notification-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres