version: '3.7'

services:
  database:
    container_name: messenger-friends-db
    image: postgres:alpine
    ports:
      - '5401:5432'
    environment:
      - POSTGRES_DB=messenger-friends-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres