server:
  port: 8081

app:
  name: auth-service
  integration-endpoints:
    person-is-blocked: http://localhost:8080/integration/friends/blocked-persons
  security:
    jwt-token:
      root-path: /api
      permit-all-endpoints:
        - route: "/api/users/register"
          method: "POST"
        - route: "/api/users/login"
          method: "POST"
      secret-key: the_best_secret_key_in_the_world_and_in_the_space
      expiration-minutes: 15
    integration:
      root-path: /integration
      api-key: 8b7390c8-d6d2-11ed-afa1-0242ac120002
  logging-requests:
    include-client-info: true
    include-query-string: true
    include-payload: true
    include-headers: true
    max-payload-length: 1000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5400/messenger-auth-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:migrations
    enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: rmq-user
    password: rmq-pass
  cloud.stream.bindings:
    createNotification-out-0:
      destination: CREATE_NOTIFICATION