server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5400/messenger-auth-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:migrations
    enabled: true
token:
  access:
    secret-key: access_secret_key
    lifetime_min: 15
  refresh:
    secret-key: refresh_secret_key
    lifetime_min: 43200
  issuer: messenger-auth-service
rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem