server:
  port: 8081

app:
  name: auth-service
  security:
    jwt-token:
      root-path: /api
      permit-all-endpoints:
        - route: "/api/users/register"
          method: "POST"
        - route: "/api/users/login"
          method: "POST"
      secret-key: the_best_secret_key_in_the_world_and_in_the_space
      expiration-minutes: 15
    integration:
      root-path: /integration
      api-key: 8b7390c8-d6d2-11ed-afa1-0242ac120002

spring:
  datasource:
    url: jdbc:postgresql://localhost:5400/messenger-auth-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:migrations
    enabled: true