server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5403/messenger-notification-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:migrations
    enabled: true