server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5401/messenger-friends-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true