server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: users
          uri: http://localhost:8081
          predicates:
            - Path=/
        - id: friends
          uri: http://localhost:8082
          predicates:
            - Path=/