server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: users1
          uri: http://localhost:8081/
          predicates:
            - Path=/api/users/**
        - id: users2
          uri: http://localhost:8081/
          predicates:
            - Path=/integration/users/**
        - id: friends1
          uri: http://localhost:8082/
          predicates:
            - Path=/api/friends/**
        - id: friends2
          uri: http://localhost:8082/
          predicates:
            - Path=/integration/friends/**

