version: '3.7'

services:
  database:
    container_name: messenger-chat-db
    image: postgres:alpine
    ports:
      - '5402:5432'
    environment:
      - POSTGRES_DB=messenger-chat-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres