version: '3.7'

services:
  database:
    container_name: messenger-auth-db
    image: postgres:alpine
    ports:
      - '5400:5432'
    environment:
      - POSTGRES_DB=messenger-auth-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres