app:
  name: core-security
  security:
    jwt-token:
      root-path: /api
      permit-all-endpoints:
      secret-key: the_best_secret_key_in_the_world_and_in_the_space
      expiration-minutes: 15
    integration:
      root-path: /integration
      api-key: 8b7390c8-d6d2-11ed-afa1-0242ac120002
