version: '3.7'

services:
  minio:
    image: bitnami/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - '9900:9000'
      - '9901:9001'
  database:
    container_name: messenger-file-storage-db
    image: postgres:alpine
    ports:
      - '5404:5432'
    environment:
      - POSTGRES_DB=messenger-file-storage-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
